package net.gearmaniacs.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF45D8ED)
val md_theme_dark_onPrimary = Color(0xFF00363D)
val md_theme_dark_primaryContainer = Color(0xFF004F58)
val md_theme_dark_onPrimaryContainer = Color(0xFF98F0FF)
val md_theme_dark_secondary = Color(0xFFE3C600)
val md_theme_dark_onSecondary = Color(0xFF393000)
val md_theme_dark_secondaryContainer = Color(0xFF524700)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE246)
val md_theme_dark_tertiary = Color(0xFFE1C629)
val md_theme_dark_onTertiary = Color(0xFF383000)
val md_theme_dark_tertiaryContainer = Color(0xFF524700)
val md_theme_dark_onTertiaryContainer = Color(0xFFFEE346)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF006874)
val md_theme_dark_surfaceTint = Color(0xFF45D8ED)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)


//val seed = Color(0xFF26C6DA)
